[build]
  # Change into your React app directory before building:
  base    = "Tripplanner_frontend"
  # Install & build with Node:
  command = "npm install && npm run build"
  # Publish the build output:
  publish = "Tripplanner_frontend/build"
