[build]
  # Delete any Pipenv triggers, then install & build your React app in the root:
  command = "rm -f Pipfile Pipfile.lock && npm install && npm run build"
  # Publish the build output from the root build folder:
  publish = "build"
