[build]
  base = "my-trip-planner"   # Netlify will run commands from this folder
  command = "npm run build"  # Builds your Vite app
  publish = "dist"           # Points to my-trip-planner/dist (no duplication)